# Generated by Django 4.2.7 on 2025-07-13 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sub_category', models.CharField(max_length=100)),
                ('case_title', models.CharField(max_length=500)),
                ('case_description', models.TextField()),
                ('applicant_name', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('current_status', models.CharField(max_length=200)),
                ('days_in_current_stage', models.IntegerField(default=0)),
                ('total_days_pending', models.IntegerField(default=0)),
                ('expected_completion', models.DateTimeField()),
                ('actual_completion', models.DateTimeField(blank=True, null=True)),
                ('status_color', models.CharField(choices=[('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red'), ('Blue', 'Blue')], default='Green', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sub_categories', models.TextField(help_text='Comma-separated sub-categories')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('expected_days', models.IntegerField(default=30)),
                ('workflow_type', models.CharField(choices=[('Type_A', 'Type A: DH → AAO → AO'), ('Type_B', 'Type B: DH → AAO → AO → Jt.CCA'), ('Type_C', 'Type C: DH → AAO → AO → Jt.CCA → CCA'), ('Type_Extended', 'Type Extended: DH → AAO → AO → Dy.CCA → Jt.CCA → CCA → Pr.CCA')], default='Type_A', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PPOMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppo_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('pension_type', models.CharField(max_length=50)),
                ('retirement_date', models.DateField()),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('branch_code', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10, unique=True)),
                ('last_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DH', 'Dealing Hand'), ('AAO', 'Assistant Accounts Officer'), ('AO', 'Accounts Officer'), ('Dy.CCA', 'Deputy Chief Controller of Accounts'), ('Jt.CCA', 'Joint Chief Controller of Accounts'), ('CCA', 'Chief Controller of Accounts'), ('Pr.CCA', 'Principal Chief Controller of Accounts'), ('ADMIN', 'Administrator')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_active_holder', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_stage', models.CharField(max_length=100)),
                ('to_stage', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('days_in_previous_stage', models.IntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cases.case')),
                ('from_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements_from', to='cases.userprofile')),
                ('to_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_to', to='cases.userprofile')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.casetype'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='current_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_cases', to='cases.userprofile'),
        ),
        migrations.AddField(
            model_name='case',
            name='last_updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='ppo_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.ppomaster'),
        ),
    ]
