# Generated by Django 4.2.7 on 2025-07-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_familymember_historicalfamilypensionclaim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familypensionclaim',
            name='claim_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalfamilypensionclaim',
            name='claim_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
