# Generated by Django 4.2.7 on 2025-07-16 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0003_alter_familymember_is_eligible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='fresh_or_compliance',
            field=models.CharField(blank=True, choices=[('fresh', 'Fresh Case'), ('compliance', 'Compliance')], max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='kyp_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='last_lc_done_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='case',
            name='mode_of_receipt',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('post', 'Post'), ('email', 'Email'), ('in_person', 'In Person')], max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='name_claimant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='name_pensioner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='original_ppo_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='ppo_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='service_book_enclosed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='type_of_correction',
            field=models.CharField(blank=True, choices=[('name_correction', 'Name Correction'), ('address_correction', 'Address Correction'), ('bank_details', 'Bank Details'), ('pension_amount', 'Pension Amount'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='case',
            name='type_of_employee',
            field=models.CharField(blank=True, choices=[('regular', 'Regular Employee'), ('contract', 'Contract Employee'), ('temporary', 'Temporary Employee'), ('consultant', 'Consultant')], max_length=20),
        ),
        migrations.AddField(
            model_name='familypensionclaim',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_family_pension_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familypensionclaim',
            name='ppo_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_pension_claims', to='cases.ppomaster'),
        ),
        migrations.AddField(
            model_name='historicalfamilypensionclaim',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfamilypensionclaim',
            name='ppo_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.ppomaster'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='is_eligible',
            field=models.BooleanField(default=False, help_text='Eligible for family pension'),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='is_eligible',
            field=models.BooleanField(default=False, help_text='Eligible for family pension'),
        ),
        migrations.CreateModel(
            name='RetiringEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('retirement_date', models.DateField()),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('basic_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pension_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_processed', models.BooleanField(default=False)),
                ('ppo_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_retiring_employees', to=settings.AUTH_USER_MODEL)),
                ('ppo_master', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiring_employee', to='cases.ppomaster')),
            ],
            options={
                'verbose_name': 'Retiring Employee',
                'verbose_name_plural': 'Retiring Employees',
                'ordering': ['retirement_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='retiring_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.retiringemployee'),
        ),
    ]
