# Generated by Django 4.2.7 on 2025-07-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_date_of_death_case_fresh_or_compliance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StageAssignment',
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_retirement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='type_of_pension',
            field=models.CharField(blank=True, choices=[('MTNL-IDA', 'MTNL-IDA'), ('DOT-CDA', 'DOT-CDA')], max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='type_of_pensioner',
            field=models.CharField(blank=True, choices=[('Superannuation/VR', 'Superannuation / VR'), ('Family Pensioner', 'Family Pensioner')], max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='mode_of_receipt',
            field=models.CharField(blank=True, choices=[('by_post', 'By Post'), ('by_hand', 'By Hand'), ('online', 'Online'), ('offline', 'Offline'), ('email', 'Email'), ('in_person', 'In Person')], max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='type_of_correction',
            field=models.CharField(blank=True, choices=[('change_of_address', 'Change Of Address'), ('change_dob_family', 'Change / Correction of DOB of Family Pensioner'), ('change_name', 'Change / Correction of Name of the Pensioner / Family Pensioner'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='type_of_employee',
            field=models.CharField(blank=True, choices=[('MTNL_IDA', 'MTNL IDA'), ('MTNL_CDA', 'MTNL CDA'), ('DOT_CDA', 'DOT CDA')], max_length=20),
        ),
    ]
