# Generated by Django 4.2.7 on 2025-07-19 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0005_delete_stageassignment_case_date_of_retirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiringemployee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retiring_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
