# Generated by Django 4.2.7 on 2025-07-20 07:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0006_alter_retiringemployee_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppomaster',
            options={'ordering': ['-date_of_retirement'], 'verbose_name': 'PPO Master', 'verbose_name_plural': 'PPO Masters'},
        ),
        migrations.RenameField(
            model_name='ppomaster',
            old_name='retirement_date',
            new_name='date_of_retirement',
        ),
        migrations.RenameField(
            model_name='ppomaster',
            old_name='name',
            new_name='employee_name',
        ),
        migrations.RemoveField(
            model_name='ppomaster',
            name='phone',
        ),
        migrations.AddField(
            model_name='ppomaster',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Invalid Aadhaar format')]),
        ),
        migrations.AddField(
            model_name='ppomaster',
            name='bank_sort_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ppomaster',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppomaster',
            name='date_of_death_family_pensioner',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppomaster',
            name='date_of_death_pensioner',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppomaster',
            name='employee_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ppomaster',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', 'Invalid IFSC format')]),
        ),
        migrations.AddField(
            model_name='ppomaster',
            name='it_pan',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]{1}$', 'Invalid PAN format')]),
        ),
        migrations.AddField(
            model_name='ppomaster',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Invalid mobile number')]),
        ),
        migrations.AddField(
            model_name='ppomaster',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ppomaster',
            name='pension_case_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ppomaster',
            name='relationship_with_pensioner',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ppomaster',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ppomaster',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ppomaster',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ppomaster',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ppomaster',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='HistoricalPPOMaster',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pension_case_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('ppo_number', models.CharField(db_index=True, max_length=20)),
                ('pension_type', models.CharField(max_length=50)),
                ('employee_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('employee_name', models.CharField(max_length=200)),
                ('date_of_retirement', models.DateField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death_pensioner', models.DateField(blank=True, null=True)),
                ('date_of_death_family_pensioner', models.DateField(blank=True, null=True)),
                ('nominee_name', models.CharField(blank=True, max_length=200)),
                ('relationship_with_pensioner', models.CharField(blank=True, max_length=50)),
                ('bank_sort_code', models.CharField(blank=True, max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('it_pan', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]{1}$', 'Invalid PAN format')])),
                ('mobile_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Invalid mobile number')])),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Invalid Aadhaar format')])),
                ('ifsc_code', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', 'Invalid IFSC format')])),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_code', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical PPO Master',
                'verbose_name_plural': 'historical PPO Masters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
