# Generated by Django 4.2.7 on 2025-07-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_ppomaster_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalppomaster',
            name='date_of_retirement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppomaster',
            name='date_of_retirement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
