# Generated by Django 4.2.7 on 2025-07-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_historicalppomaster_date_of_retirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalppomaster',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ppomaster',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
