# Generated by Django 4.2.7 on 2025-07-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_historicalppomaster_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalppomaster',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalppomaster',
            name='bank_sort_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalppomaster',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalppomaster',
            name='relationship_with_pensioner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ppomaster',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ppomaster',
            name='bank_sort_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ppomaster',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ppomaster',
            name='relationship_with_pensioner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
