# Generated by Django 4.2.7 on 2025-07-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_alter_historicalppomaster_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_id'], name='cases_case_case_id_e77ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['ppo_number'], name='cases_case_ppo_num_c38fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['current_holder', 'is_completed'], name='cases_case_current_4ed586_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority', 'status_color'], name='cases_case_priorit_318013_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['registration_date'], name='cases_case_registr_b18050_idx'),
        ),
        migrations.AddIndex(
            model_name='ppomaster',
            index=models.Index(fields=['ppo_number'], name='cases_ppoma_ppo_num_a60042_idx'),
        ),
        migrations.AddIndex(
            model_name='ppomaster',
            index=models.Index(fields=['employee_number'], name='cases_ppoma_employe_0cc940_idx'),
        ),
        migrations.AddIndex(
            model_name='ppomaster',
            index=models.Index(fields=['employee_name'], name='cases_ppoma_employe_f1f62c_idx'),
        ),
        migrations.AddIndex(
            model_name='ppomaster',
            index=models.Index(fields=['pension_case_number'], name='cases_ppoma_pension_30adf5_idx'),
        ),
    ]
