# Generated by Django 4.2.7 on 2025-07-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_case_cases_case_case_id_e77ffb_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='case',
            name='manual_mobile',
            field=models.CharField(blank=True, help_text='Mobile Number (manual entry)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='registered_mobile',
            field=models.CharField(blank=True, help_text='Registered Mobile Number from PPO Master', max_length=15, null=True),
        ),
    ]
