# Generated by Django 4.2.7 on 2025-07-27 02:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_remove_case_mobile_number_case_manual_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CaseTypeFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_configs', to='cases.casetype')),
            ],
            options={
                'ordering': ['case_type', 'field_name'],
                'unique_together': {('case_type', 'field_name')},
            },
        ),
    ]
