# Generated by Django 4.2.7 on 2025-07-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_casetype_created_at_casetypefieldconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casetypefieldconfig',
            options={'ordering': ['case_type', 'order', 'field_name']},
        ),
        migrations.AddField(
            model_name='casetype',
            name='auto_subcategory',
            field=models.CharField(blank=True, help_text='Auto-generated subcategory', max_length=100),
        ),
        migrations.AddField(
            model_name='casetype',
            name='default_priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='casetype',
            name='requires_ppo',
            field=models.BooleanField(default=False, help_text='Whether this case type requires PPO'),
        ),
        migrations.AddField(
            model_name='casetypefieldconfig',
            name='data_source',
            field=models.CharField(blank=True, help_text='Source of data: ppo_master, retiring_employee, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='casetypefieldconfig',
            name='is_readonly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casetypefieldconfig',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order for fields'),
        ),
    ]
