# Generated by Django 4.2.7 on 2025-07-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_alter_casetypefieldconfig_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='manual_mobile',
        ),
        migrations.RemoveField(
            model_name='case',
            name='registered_mobile',
        ),
        migrations.RemoveField(
            model_name='casetype',
            name='auto_subcategory',
        ),
        migrations.RemoveField(
            model_name='casetype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='casetype',
            name='default_priority',
        ),
        migrations.RemoveField(
            model_name='casetype',
            name='requires_ppo',
        ),
        migrations.AddField(
            model_name='case',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.DeleteModel(
            name='CaseTypeFieldConfig',
        ),
    ]
