# Generated by Django 4.2.7 on 2025-07-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_remove_case_manual_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='casetype',
            name='required_fields',
            field=models.ManyToManyField(blank=True, to='cases.fieldsetting'),
        ),
    ]
