# Generated by Django 4.2.7 on 2025-07-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_fieldsetting_casetype_required_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fieldsetting',
            options={'ordering': ['label'], 'verbose_name': 'Field Setting', 'verbose_name_plural': 'Field Settings'},
        ),
        migrations.AlterField(
            model_name='casetype',
            name='required_fields',
            field=models.ManyToManyField(blank=True, help_text='Fields required for this case type', to='cases.fieldsetting'),
        ),
    ]
