# Generated by Django 4.2.7 on 2025-07-29 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_alter_casetype_options_alter_fieldsetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to='case_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_data', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(max_length=200)),
                ('milestone_description', models.TextField(blank=True)),
                ('expected_days', models.IntegerField(default=1, help_text='Expected days to complete this milestone')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('milestone_order', models.IntegerField(default=0)),
                ('responsible_role', models.CharField(choices=[('DH', 'Dealing Hand'), ('AAO', 'Assistant Accounts Officer'), ('AO', 'Accounts Officer'), ('Dy.CCA', 'Deputy Chief Controller of Accounts'), ('Jt.CCA', 'Joint Chief Controller of Accounts'), ('CCA', 'Chief Controller of Accounts'), ('Pr.CCA', 'Principal Chief Controller of Accounts'), ('ADMIN', 'Administrator')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['milestone_order', 'milestone_name'],
            },
        ),
        migrations.CreateModel(
            name='CaseMilestoneProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('expected_completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='milestone_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_milestones', to='cases.userprofile')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_progress', to='cases.case')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_milestones', to='cases.userprofile')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.casemilestone')),
            ],
            options={
                'ordering': ['milestone__milestone_order'],
                'unique_together': {('case', 'milestone')},
            },
        ),
        migrations.CreateModel(
            name='DynamicFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select Dropdown'), ('checkbox', 'Checkbox'), ('radio', 'Radio Button'), ('file', 'File Upload')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('help_text', models.TextField(blank=True)),
                ('choices', models.TextField(blank=True, help_text='One option per line for select/radio fields')),
                ('data_source', models.CharField(choices=[('manual', 'Manual Entry'), ('ppo_master', 'PPO Master'), ('retiring_employee', 'Retiring Employee'), ('database_query', 'Database Query')], default='manual', max_length=20)),
                ('source_field', models.CharField(blank=True, help_text='Field name from data source', max_length=100)),
                ('field_order', models.IntegerField(default=0)),
                ('field_group', models.CharField(blank=True, help_text='Group related fields together', max_length=100)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('regex_pattern', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['field_order', 'field_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='casetype',
            options={},
        ),
        migrations.RemoveField(
            model_name='casetype',
            name='required_fields',
        ),
        migrations.DeleteModel(
            name='FieldSetting',
        ),
        migrations.AddField(
            model_name='dynamicformfield',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to='cases.casetype'),
        ),
        migrations.AddField(
            model_name='casemilestone',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='cases.casetype'),
        ),
        migrations.AddField(
            model_name='casefielddata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.dynamicformfield'),
        ),
        migrations.AlterUniqueTogether(
            name='dynamicformfield',
            unique_together={('case_type', 'field_name')},
        ),
        migrations.AlterUniqueTogether(
            name='casemilestone',
            unique_together={('case_type', 'milestone_name')},
        ),
        migrations.AlterUniqueTogether(
            name='casefielddata',
            unique_together={('case', 'field')},
        ),
    ]
