# Generated by Django 4.2.7 on 2025-08-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_location_record_alter_casemilestone_responsible_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_record_keeper',
            field=models.BooleanField(default=False, help_text='Designates this user as responsible for handing over and receiving physical records.'),
        ),
        migrations.AlterField(
            model_name='casemilestone',
            name='responsible_role',
            field=models.CharField(choices=[('DH', 'Dealing Hand'), ('AAO', 'Assistant Accounts Officer'), ('AO', 'Accounts Officer'), ('Dy.CCA', 'Deputy Chief Controller of Accounts'), ('Jt.CCA', 'Joint Chief Controller of Accounts'), ('CCA', 'Chief Controller of Accounts'), ('Pr.CCA', 'Principal Chief Controller of Accounts'), ('ADMIN', 'Administrator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('DH', 'Dealing Hand'), ('AAO', 'Assistant Accounts Officer'), ('AO', 'Accounts Officer'), ('Dy.CCA', 'Deputy Chief Controller of Accounts'), ('Jt.CCA', 'Joint Chief Controller of Accounts'), ('CCA', 'Chief Controller of Accounts'), ('Pr.CCA', 'Principal Chief Controller of Accounts'), ('ADMIN', 'Administrator')], max_length=20),
        ),
    ]
