# Generated by Django 4.2.7 on 2025-08-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_userprofile_is_record_keeper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecordrequisition',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending AAO Approval'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved (Pending Handover)'), ('IN_TRANSIT', 'In Transit'), ('IN_USE', 'In Use (Handed Over)'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURNED', 'Returned (Closed)'), ('RETURN_REJECTED', 'Return Rejected')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='recordrequisition',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending AAO Approval'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved (Pending Handover)'), ('IN_TRANSIT', 'In Transit'), ('IN_USE', 'In Use (Handed Over)'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURNED', 'Returned (Closed)'), ('RETURN_REJECTED', 'Return Rejected')], default='PENDING_APPROVAL', max_length=20),
        ),
    ]
