# Generated by Django 4.2.7 on 2025-08-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_alter_historicalrecordrequisition_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordmovement',
            name='requisition',
            field=models.ForeignKey(blank=True, help_text='The requisition that authorized this movement.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cases.recordrequisition'),
        ),
    ]
