# Generated by Django 4.2.7 on 2025-08-02 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0024_alter_recordmovement_requisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the grievance mode.', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to hide this mode from forms.')),
            ],
            options={
                'verbose_name': 'Grievance Mode',
                'verbose_name_plural': 'Grievance Modes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalGrievance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('grievance_id', models.CharField(db_index=True, help_text='A unique ID for the grievance.', max_length=50)),
                ('complainant_name', models.CharField(max_length=200)),
                ('complainant_contact', models.CharField(blank=True, help_text='Phone number or email address.', max_length=100)),
                ('grievance_text', models.TextField(help_text='The full text of the complaint.')),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACTION_INITIATED', 'Action Initiated (Case Created)'), ('DISPOSED', 'Disposed')], default='NEW', max_length=20)),
                ('disposal_type', models.CharField(blank=True, choices=[('INTERIM_REPLY', 'Interim Reply'), ('FINAL_REPLY', 'Final Reply')], max_length=20, null=True)),
                ('reply_details', models.TextField(blank=True, help_text='Details of the interim or final reply provided.')),
                ('date_disposed', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('generated_case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.case')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mode_of_receipt', models.ForeignKey(blank=True, db_constraint=False, help_text='How the grievance was received.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.grievancemode')),
                ('pensioner', models.ForeignKey(blank=True, db_constraint=False, help_text='The pensioner this grievance relates to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.ppomaster')),
            ],
            options={
                'verbose_name': 'historical Grievance',
                'verbose_name_plural': 'historical Grievances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grievance_id', models.CharField(db_index=True, help_text='A unique ID for the grievance.', max_length=50, unique=True)),
                ('complainant_name', models.CharField(max_length=200)),
                ('complainant_contact', models.CharField(blank=True, help_text='Phone number or email address.', max_length=100)),
                ('grievance_text', models.TextField(help_text='The full text of the complaint.')),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACTION_INITIATED', 'Action Initiated (Case Created)'), ('DISPOSED', 'Disposed')], default='NEW', max_length=20)),
                ('disposal_type', models.CharField(blank=True, choices=[('INTERIM_REPLY', 'Interim Reply'), ('FINAL_REPLY', 'Final Reply')], max_length=20, null=True)),
                ('reply_details', models.TextField(blank=True, help_text='Details of the interim or final reply provided.')),
                ('date_disposed', models.DateField(blank=True, null=True)),
                ('generated_case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_grievance', to='cases.case')),
                ('mode_of_receipt', models.ForeignKey(help_text='How the grievance was received.', on_delete=django.db.models.deletion.PROTECT, to='cases.grievancemode')),
                ('pensioner', models.ForeignKey(help_text='The pensioner this grievance relates to.', on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='cases.ppomaster')),
            ],
            options={
                'verbose_name': 'Grievance',
                'verbose_name_plural': 'Grievances',
                'ordering': ['-date_received'],
            },
        ),
    ]
