# Generated by Django 4.2.7 on 2025-08-03 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_grievancemode_historicalgrievance_grievance'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grievances', to='cases.userprofile'),
        ),
        migrations.AddField(
            model_name='historicalgrievance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.userprofile'),
        ),
    ]
