# Generated by Django 4.2.7 on 2025-08-03 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0026_grievance_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grievances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgrievance',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
