# Generated by Django 4.2.7 on 2025-08-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_grievance_created_by_historicalgrievance_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalgrievance',
            name='created_by',
        ),
    ]
