# Generated by Django 4.2.7 on 2025-08-03 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0028_remove_grievance_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The officer this grievance is initially assigned to for action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.userprofile'),
        ),
        migrations.AlterField(
            model_name='historicalgrievance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The officer this grievance is initially assigned to for action.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.userprofile'),
        ),
    ]
