# Generated by Django 4.2.7 on 2025-08-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0029_alter_grievance_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The user this grievance is currently assigned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grievances', to='cases.userprofile'),
        ),
        migrations.AlterField(
            model_name='historicalgrievance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user this grievance is currently assigned to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.userprofile'),
        ),
    ]
