# Generated by Django 4.2.7 on 2025-08-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_administrativeworkflow_documentcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='file_number',
            field=models.CharField(help_text='Unique file identification number', max_length=50, unique=True),
        ),
    ]
