# Generated by Django 4.2.7 on 2025-08-04 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0032_alter_record_file_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who originally registered the grievance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grievances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgrievance',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user who originally registered the grievance.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
